### ISSUE TITLE
Initial sensor readings of 0 on HA restart

### ISSUE THREAD

**Issue by EK701** [vincenzosuraci/hassio_shelly_cloud#2]
I'm running HA in a docker container under Ubuntu.  Everything is working fine, except every time HA is restarted, the initial sensor reading from all sensors is 0.

**Comment by EK701** [comment]
Shelly Smart Home version 0.1.0
HA version 0.99.3

**Comment by vincenzosuraci** [comment]
That's true. It is a limit in my code. You have to wait until the first scan_interval to ensure that the reading is done for the first time. I did it having in mind that ha should be running 24/7

**Comment by EK701** [comment]
Can you point me to the section in your code where I could modify this?

Thanks!
